include:
  - template: Code-Quality.gitlab-ci.yml

image: node:latest

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

prettier:
  before_script:
    - npm install
  stage: test
  script:
    - npm run prettier

lint:
  before_script:
    - npm install
  stage: test
  script:
    - npm run lint

flow:
  before_script:
    - npm install
  stage: test
  script:
    - npm run flow

npm audit:
  before_script:
    - npm install
  stage: test
  script:
    - npm audit

build:
  before_script:
    - npm install
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - /dist
    expire_in: 30 days
